### PR TITLE
php rename

### PR DESCRIPTION
**Pull request by nburd90**
Switched the html files to php.

### CODE REVIEW

**Review by billythakidd04 — CHANGES_REQUESTED** [review]
Need to fix whatever conflicts exist

`git checkout main`
`git pull -p`
`git checkout php-rename`
`git merge main`
fix commits
`git add <files>`
`git push`

**Comment by billythakidd04** [comment]
This should not have been merged yet. There was no approval. Need branch protections.

**Comment by nburd90** [comment]
I put it on for branch main. Do I have to create a branch protection for
every branch that’s exists?

**Comment by billythakidd04** [comment]
No but you should check if the rule is matching any branches... message me if you have a question

**Pull request merged**
